Feature monitor
samply/beam pull request #123
Opened 2023-04-13 11:21 UTC by Threated

This is a first draft of the task progress monitoring at proxy level

2023-06-02 12:58 UTC, TKussel requested changes
Please add some lines of documentation to the Readme

2023-06-02 13:10 UTC, Threated commented on proxy/monitor/README.md
Yeah I forgot to remove the boilerplate Readme that the inital codegen generates

2023-06-13 13:47 UTC, Threated commented
I will write something about this in the Readme once #123 is merged as only than I will know how the final CI and docker image name will look like. I will than need to rebase this branch as there were a lot of changes since this code was written.

2023-06-22 13:19 UTC, Threated commented
As there have been some developments regarding adding more app specific visualization to the monitoring I suggest to extract the frontend of this PR into its own application and just provide the required endpoint.

2023-06-22 13:47 UTC, TKussel commented
I fully agree. A separation between a) the publication of the event stream (this PR) and b) the visualization of the data (in a separate repository) is a smart idea to keep Beam's responsibilities concise.

2023-07-03 14:29 UTC, closed without merging

2023-07-03 14:32 UTC, Threated commented
Closed in favor of [beam-inspector](https://github.com/samply/beam-inspector) and [this branch](https://github.com/samply/beam/tree/feature/beam-inspector)