Release Samply.Beam 0.7.0
samply/beam pull request #158
Opened 2023-08-23 11:14 UTC by TKussel

2023-08-23 11:37 UTC, Threated approved these changes

2023-09-07 10:47 UTC, lablans requested changes
First part of review

2023-09-07 10:47 UTC, lablans requested changes
Second part of review

2023-09-07 10:48 UTC, lablans commented
Third part of review ETA today/tomorrow

2023-09-14 14:33 UTC, lablans commented on README.md
> +- `from`: BeamID of the client who requested the socket connection
```suggestion
- `from`: BeamID of the client requesting the socket connection
```

2023-09-14 14:35 UTC, lablans commented on README.md
> +```
```suggestion
In case of a successful connection between proxy and broker, the call returns `HTTP/1.1 200`, otherwise `HTTP/1.1 404`.
```

2023-09-14 14:36 UTC, lablans commented on README.md
> +> Note: Only available on builds with the feature `sockets` enabled. Both proxy and broker need to be built with this flag. There are also prebuild docker images available with this feature.
```suggestion
> Note: Only available on builds with the feature `sockets` enabled. Both proxy and broker need to be built with this flag. There are also prebuilt docker images available with this feature.
```

2023-09-14 14:37 UTC, lablans commented on README.md
> +Header: `Upgrade` is required
Example content of this header?

2023-09-14 14:37 UTC, lablans commented on README.md
> + * The same parameters as for long-polling, i.e. to, from, filter=todo, wait_count, and wait_time are supported.
```suggestion
 * The same parameters as for long-polling, i.e. `to`, `from`, `filter=todo`, `wait_count` and `wait_time` are supported.
```

2023-09-14 14:45 UTC, lablans commented on CHANGELOG.md
> +
```suggestion
* *Certificate Management:* Support for revocation of Beam certificates. Enhanced cert management companion tools.

```

2023-09-14 14:47 UTC, lablans commented on shared/src/serializing_compatability_test.rs
Compatibility is spelled incorrectly

2023-09-27 13:43 UTC, lablans commented on shared/src/serializing_compatability_test.rs
Fixed in f8e17a2af22828f7095c8b741766e835e387fd45

2023-09-28 06:17 UTC, TKussel commented on README.md
> +Header: `Upgrade` is required
I discussed this with Jan a while ago. The standard requires the header to be set, but does not mandate a value. This is how we handle the header as well. I did not want to make the assumption of more restrictions than the standard imposes.

How would you read 
"Header `Upgrade` is required, e.g., `Upgrade: true`"?

2023-09-28 08:08 UTC, TKussel commented on README.md
> +### Socket Task
See https://github.com/samply/beam/pull/168

2023-09-28 08:08 UTC, TKussel commented on README.md
> +Header: `Upgrade` is required
See https://github.com/samply/beam/pull/168

2023-09-28 08:09 UTC, TKussel commented
Review comments have been adressed in https://github.com/samply/beam/pull/168

2023-10-02 07:56 UTC, lablans approved these changes
Some last suggestions -- just apply -- then this can be merged.

2023-10-02 07:56 UTC, lablans commented on README.md
> +- `ttl`: The time-to-live of this socket task. After this time has elapsed the recipient can no longer connect to the socket. (Already established connections are not affected)
```suggestion
- `ttl`: The time-to-live of this socket task. After this time has elapsed the recipient can no longer connect to the socket. Already established connections are not affected.
```

2023-10-02 07:56 UTC, lablans commented on README.md
> +A dev environment is provided consisting of one broker and two proxies as well as an optional MITM proxy (listening on `localhost:9090`) for debugging. As the MITM proxy interferes with SSE, it is co
```suggestion
A dev environment is provided consisting of one broker and two proxies as well as an optional MITM proxy (listening on `localhost:9090`) for debugging. To use it, remove the comment signs for the MITM service and the `ALL_PROXY` environment variables in `dev/docker-compose.yml`. Note that the MITM proxy interferes with SSE. 
```

2023-10-02 07:56 UTC, lablans commented on README.md
> +- [x] Direct-Socket connections
```suggestion
- [x] Transport direct socket connections
```

2023-10-02 07:56 UTC, lablans commented on README.md
> +- [ ] Efficient file transfer for large data
```suggestion
- [ ] File transfers (with efficient support for large files)
```

2023-10-02 07:56 UTC, lablans commented on README.md
> +- [ ] Broker-side filtering of the unencrypted metadata fields with JSON queries
```suggestion
- [ ] Broker-side filtering of tasks using the unencrypted metadata fields (probably using JSON queries)
```

2023-10-02 08:21 UTC, lablans commented on CHANGELOG.md
> +This version, Samply.Beam 0.7.0, has long been in the making and introduces multiple improvements, new features, and bug fixes. In particular, we are thrilled to introduce the possibility to use Samp
```suggestion
This major release features almost 300 commits introducing multiple improvements, new features, and bug fixes. In particular, we are thrilled to introduce the possibility to use Samply.Beam for secure and easy *direct socket connections*. This opens Samply.Beam for many additional use cases, where a message-passing approach is not suitable, e.g. applications with high bandwidth demands.
```

2023-10-04 06:56 UTC, merged